<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
      <GenerateDocumentationFile>true</GenerateDocumentationFile>
      <NoWarn>$(NoWarn)</NoWarn>
    <UserSecretsId>aspnet-Web-ffe0c3ca-976d-495a-b5e9-eb12e568bffd</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="9.*" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.*" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="9.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.*" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="MudBlazor" Version="8.*" />
    <PackageReference Include="Extensions.MudBlazor.StaticInput" Version="3.2.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
  </ItemGroup>


  <ItemGroup>
    <Folder Include="Migrations\" />
    <Folder Include="Security\" />
  </ItemGroup>


  <ItemGroup>
    <_ContentIncludedByDefault Remove="Layout\LoginLayout.razor" />
    <_ContentIncludedByDefault Remove="Layout\MainLayout.razor" />
    <_ContentIncludedByDefault Remove="Layout\NavMenu.razor" />
    <_ContentIncludedByDefault Remove="Components\Layout\MainLayout.razor" />
    <_ContentIncludedByDefault Remove="Components\Layout\NavMenu.razor" />
    <_ContentIncludedByDefault Remove="Components\Account\Pages\Manage\ChangePassword.razor" />
    <_ContentIncludedByDefault Remove="Components\Account\Pages\Manage\DeletePersonalData.razor" />
    <_ContentIncludedByDefault Remove="Components\Account\Pages\Manage\Disable2fa.razor" />
    <_ContentIncludedByDefault Remove="Components\Account\Pages\Manage\Email.razor" />
    <_ContentIncludedByDefault Remove="Components\Account\Pages\Manage\EnableAuthenticator.razor" />
    <_ContentIncludedByDefault Remove="Components\Account\Pages\Manage\ExternalLogins.razor" />
    <_ContentIncludedByDefault Remove="Components\Account\Pages\Manage\GenerateRecoveryCodes.razor" />
    <_ContentIncludedByDefault Remove="Components\Account\Pages\Manage\Index.razor" />
    <_ContentIncludedByDefault Remove="Components\Account\Pages\Manage\PersonalData.razor" />
    <_ContentIncludedByDefault Remove="Components\Account\Pages\Manage\ResetAuthenticator.razor" />
    <_ContentIncludedByDefault Remove="Components\Account\Pages\Manage\SetPassword.razor" />
    <_ContentIncludedByDefault Remove="Components\Account\Pages\Manage\TwoFactorAuthentication.razor" />
    <_ContentIncludedByDefault Remove="Components\Account\Pages\Manage\_Imports.razor" />
  </ItemGroup>


  <ItemGroup>
    <AdditionalFiles Include="Layout\MainLayout.razor" />
    <AdditionalFiles Include="Layout\NavMenu.razor" />
    <AdditionalFiles Include="Pages\Auth.razor" />
    <AdditionalFiles Include="Pages\NoInteractive\Login.razor" />
    <AdditionalFiles Include="Pages\NoInteractive\_Imports.razor" />
  </ItemGroup>

</Project>